import { environment } from './../environments/environment';

export const FixedRoutes = {
  Login: `login`,
  Patient: `patient`,
  PatientEdit: `patientedit`,
  PatientRegister: `patientregister`,
  Dashboard: `dashboard`,
  Appointment: `appointment`,
  AppointmentDetails: `details`,
  MyClinic: `clinic`,
  ErPatient: `erpatient`,
  MyClinicDetails: `details`,
  Order: `order`,
  OrderDetails: `details`,
  Voucher: `voucher`,
  Datamaintenance:`data-maintenance`,
  Settings: `settings`,
  CrudService: `crudservice`,
  CrudConsultant: `crudconsultant`,
  CrudAppointment: `crudappointment`,
  CrudPatientId: `crudpatientid`,
  CrudRelationtype: `crudrelationtype`,
  Service: `service`,
  PatientRelations: `patient-relation`,
  PatientIdTypes: `patient-id-types`,
  ConsultationDetails: `consultation-details`,
  AppointmentsDetails: `appointments-details`,
  ServiceRegister: `serviceregister`,
  RegisterConsultation: `registerconsultation`,
  AppontmentType: `appointmentregister`,
  ServiceEdit: `editservice`,
  AppointmentEdit: `appointmentedit`,
  ConsultationData: `consultationdata`,
  Consultation: `consultation`,
  ConsultationEdit: `consultationedit`,
  PatientIdRegister: `patientidregister`,
  PatientIdEdit: `patientIdedit`,
  RegisterRelation: `registerrelation`,
  RegisterRelationEdit: `registerrelationedit`,
  DoctorDashboard: `doctor-dashboard`,
  PharmacistDashboard: `pharmacist-dashboard`,
  InpatientRegistration: `inpatient-registration`,
  Admittedpatient: `admitted-patient`,
  AdmittedpatientDetails: `admitted-patient-details`,
  DischargedPatients: `discharged-patients`,
  EditdischargePopup: `edit-discharge-popup`,
  Erpatientdetails: `emergency-patient-detail`,
  Pharmacy:`pharmacy`,
  Radiology:`radiology`,
  laboratory :`laboratory`,
  laboratoryDetails:`details`,
  RadiologyDetails:`details`,
  PharmacyDetails:`details`,
  paymentHeader:`payment-details`,
  Reports:`reports`,
};

export const FixedRoutesAdmin = {
  Appointment: `appointment`,
  Patient: `patient`,
  PatientRegister: `patient/patientregister`,
  Order: `order`,
  Settings: `settings`,
  Datamaintenance:`data-maintenance`
};

export const FixedRoutesMaster = {
  Dashboard: `dashboard`,
  Appointment: `appointment`,
  Patient: `patient`,
  MyClinic: `clinic`,
  Order: `order`,
  ErPatient: `erpatient`,
  Voucher: `voucher`,
  Settings: `settings`,
  DischargedPatients: `discharged-patients`,
  InpatientRegistration: `inpatient-registration`,
  Admittedpatient: `admitted-patient`,
  Datamaintenance:`data-maintenance`,
  laboratory:`laboratory`,
  Radiology:`radiology`,
  Reports:`reports`,
  Pharmacy:`pharmacy`
};

export const FixedRoutesPharmacist = {
  PharmacistDashboard: `pharmacist-dashboard`,
  // MyClinic: `clinic`,
  Datamaintenance:`data-maintenance`,
   Patient: `patient`,
  // Appointment: `appointment`,
  Order: `order`,
  Pharmacy:`pharmacy`
  // Voucher: `voucher`,
  // Settings: `settings`,
};

export const FixedRoutesDoctor = {
  // DoctorDashboard: `doctor-dashboard`,
  MyClinic: `clinic`,
  // Appointment: `appointment`,
  // Patient: `patient`,
  // Order: `order`,
  // Voucher: `voucher`,
  // Settings: `settings`,
};

export const FixedRoutesNursing = {
  // Appointment: `appointment`,
  // MyClinic: `clinic`,
  ErPatient: `erpatient`,
};

export const Operations = {
  Sample: `/Sample`,
  Import: `/Import`,
  Export: `/Export`,
  Document: `/Document`,
  Download: `/Download`,
};

export const OPDoctor = {
  MyClinic: `clinic`,
  ErPatient: `erpatient`,
  Admittedpatient: `admitted-patient`
};

export const Clerk = {
  // Dashboard: `dashboard`,
  Appointment: `appointment`,
  // MyClinic: `clinic`,
  ErPatient: `erpatient`,
  // Voucher: `voucher`,
  // Settings: `settings`,
  // DischargedPatients: `discharged-patients`,
  // InpatientRegistration: `inpatient-registration`,
  Admittedpatient: `admitted-patient`,
  Patient: `patient`
};

export const SeniorClerk ={
  Appointment: `appointment`,
  ErPatient: `erpatient`,
    Patient: `patient`
}
export const FixedRoutesUsers = {
  // Dashboard: `dashboard`,
  Appointment: `appointment`,
  MyClinic: `clinic`,
  ErPatient: `erpatient`,
  Voucher: `voucher`,
  Settings: `settings`,
  DischargedPatients: `discharged-patients`,
  InpatientRegistration: `inpatient-registration`,
  Admittedpatient: `admitted-patient`
};
export const Hospitalist ={
  ErPatient: `erpatient`,
  DischargedPatients: `discharged-patients`,
  Admittedpatient: `admitted-patient`
}
export const Cashier = {
  Order: `order`,
};
export const CashierLevel1 = {
  Order:`order`,
  Admittedpatient: `admitted-patient`,
  Reports: `reports`
}
export const CashierLevel2 = {
  Order:`order`,
  Admittedpatient: `admitted-patient`
}
export const SeniorCashier = {
  Order: `order`,
  Admittedpatient: `admitted-patient`
};
export const LabTechnician={
laboratory:`laboratory`,
 Patient: `patient`
}
export const RadTencnician={
  Radiology:`radiology`,
   Patient: `patient`
}
export const Modules = {
  Base: environment.apiURL,
  Images: `${environment.apiURL}Healthcare/`,
  AuthUrl: `${environment.apiURL}api/Auth`,
  OptionsUrl: `${environment.apiURL}api/Option`,
  Patient: `${environment.apiURL}api/Patient`,
  PatientById: `${environment.apiURL}api/Patient/ById`,
  PatientSearch: `${environment.apiURL}api/Patient/Search`,
  PatientInClinic: `${environment.apiURL}api/Patient/InClinic`,
  PatientInOrder: `${environment.apiURL}api/Patient/InOrder`,
  PatientByAppointment: `${environment.apiURL}api/Patient/ByAppointment`,
  Appointment: `${environment.apiURL}api/Appointment`,
  AppointmentCancel: `${environment.apiURL}api/Appointment/Cancel`,
  AppointmentByDate: `${environment.apiURL}api/Appointment/ByDate`,
  DownloadAppoinmentList: `${environment.apiURL}api/Appointment/Download`,
  AppointmentByDateRange: `${environment.apiURL}api/Appointment/ByDateRange`,
  AppointmentSlotByDate: `${environment.apiURL}api/Appointment/SlotByDate`,
  AppointmentInClinic: `${environment.apiURL}api/Appointment/InClinic`,
  AppointmentPatientInClinic: `${environment.apiURL}api/Appointment/SetInClinic`,
  AppointmentPatientCloseEncounter: `${environment.apiURL}api/Appointment/SetClosedEncounter`,
  SystemCount: `${environment.apiURL}api/Dashboard/SystemCounts`,
  ActiveServices: `${environment.apiURL}api/Service`,
  ActiveConsultation: `${environment.apiURL}api/Consultation`,
  CreateOrder: `${environment.apiURL}api/Order`,
  AppointmentCounts: `${environment.apiURL}api/Dashboard/AppointmentCounts`,
  PaymentOrder: `${environment.apiURL}api/Order/Payment`,
  Documentation: `${environment.apiURL}api/Document`,
  GenerateQRCode: `${environment.apiURL}api/Utility/GenerateQR`,
  PatientCard: `${environment.apiURL}api/Patient/SendCard`,
  RhinoDocument: `${environment.apiURL}api/Document/ConsultationDocument`,
  FaceNeckDocument: `${environment.apiURL}api/Document/FaceNeckDocument`,
  SurgeryProcedureDocument: `${environment.apiURL}api/Document/SurgeryProcedureDocument`,
  AttachmentDocument: `${environment.apiURL}api/Document/AttachmentDocument`,
  GeneralDocument: `${environment.apiURL}api/Document/GeneralDocument`,
  OrderByPatientId: `${environment.apiURL}api/Order/ByPatientId`,
  DeleteGeneralDocument: `${environment.apiURL}api/Document/DeleteGeneralDocument`,
  DeleteConsultationDocument: `${environment.apiURL}api/Document/DeleteConsultationDocument`,
  DeleteSurgeryProcedureDocument: `${environment.apiURL}api/Document/DeleteSurgeryProcedureDocument`,
  DeleteAttachmentDocument: `${environment.apiURL}api/Document/DeleteAttachmentDocument`,
  Voucher: `${environment.apiURL}api/Vouchers`,
  GetVoucherByPatientId: `${environment.apiURL}api/Patient/GetVoucher`,
  VoucherNumber: `${environment.apiURL}api/Vouchers/ByNumber`,
  PatientRelationship: `${environment.apiURL}api/PatientRelationship`,
  PatientRelationshipById: `${environment.apiURL}api/PatientRelationship/ById`,
  ConsultationById: `${environment.apiURL}api/Consultation/ById`,
  AppointmentType: `${environment.apiURL}api/AppointmentType`,
  AppointmentTypeById: `${environment.apiURL}api/AppointmentType/ById`,
  PatientType: `${environment.apiURL}api/PatientIdType`,
  PatientTypeById: `${environment.apiURL}api/PatientIdType/ById`,
  Service: `${environment.apiURL}api/Service`,
  Consultation: `${environment.apiURL}api/Consultation`,
  ServiceById: `${environment.apiURL}api/Service/ById`,
  GetSpecialities: `${environment.apiURL}api/Appointment/GetSpecialities`,
  GetGetDoctor: `${environment.apiURL}api/Appointment/GetGetDoctor`,
  ByDateRangeAndDocCode: `${environment.apiURL}api/Appointment/ByDateRangeAndDocCode`,
  soapDocument: `${environment.apiURL}api/Document/SoapNoteDocuments`,
  slotByDateAndDoctCode: `${environment.apiURL}api/Appointment/SlotByDateAndDoctCode`,
  ByDateAndDoctCode: `${environment.apiURL}api/Appointment/ByDateAndDoctCode`,
  visitNoteDocument: `${environment.apiURL}api/Document/VisitNoteDocuments`,
  patientRoomsAssigned: `${environment.apiURL}api/Patient/PatientRoomsAssigned`,
  getFloors: `${environment.apiURL}api/Hospital/GetFloors`,
  getRooms: `${environment.apiURL}api/Hospital/GetRooms`,
  getBads: `${environment.apiURL}api/Hospital/GetBads`,
  checkBadsBookedOrNot: `${environment.apiURL}api/Hospital/CheckBadsBookedOrNot`,
  getSelectCaseTypesTbl: `${environment.apiURL}api/Patient/GetSelectCaseTypesTbl`,
  getSelectAdmissionTypesTbl: `${environment.apiURL}api/Patient/GetSelectAdmissionTypesTbl`,
  saveAdmittedPatient: `${environment.apiURL}api/Patient/PatientRoomsAssigned`,
  getAdmissionStatus: `${environment.apiURL}api/Patient/GetAdmissionStatus`,
  getPatientRoomList: `${environment.apiURL}api/Patient/PatientRoomsAssignedList`,
  getALLEmergencypatientByDate: `${environment.apiURL}api/Patient/GetALLEmergencypatientByDate`,
  getSpeciality: `${environment.apiURL}api/Specialities`,
  getErPatient: `${environment.apiURL}api/Patient/EmergencypatientRoomsCheckinCheckout`,
  getAttendingPhysician: `${environment.apiURL}api/Doctors`,
  nationality: `${environment.apiURL}api/Countries`,
  cancelAdmission: `${environment.apiURL}api/Patient/PatientRoomsAssignedCancel`,
  saveTransferPatient: `${environment.apiURL}api/Patient/PatientTransfer`,
  getTransferTypes: `${environment.apiURL}api/Patient/GetTransferTypes`,
  getTransferStatuses: `${environment.apiURL}api/Patient/GetTransferStatuses`,
  getDischargeType: `${environment.apiURL}api/Patient/GetDischargeTypes`,
  PatientDischargeList: `${environment.apiURL}api/Patient/PatientDischargeList`,
  getDischargeStatus: `${environment.apiURL}api/Patient/GetDischargeStatuses`,
  getDischargeTypes: `${environment.apiURL}api/Patient/GetDischargeTypes`,
  saveDischargePatient: `${environment.apiURL}api/Patient/PatientPatientDischarge`,
  cancelDischargedPatient: `${environment.apiURL}api/Patient/PatientPatientDischargeCancel`,
  getByOrderId: `${environment.apiURL}api/Order/OrderById`,
  getVisitStatus: `${environment.apiURL}api/Patient/VisitStatus`,
  updateStatus: `${environment.apiURL}api/Patient/UpdateVisitStatus`,
  cancelErPatient: `${environment.apiURL}api/Patient/PatientRoomsAssignedCancel`,
  getInvoiceData: `${environment.apiURL}api/Order/OrderById`,
  getServiceHistory: `${environment.apiURL}api/Patient/ById`,
  getHearAboutUs:`${environment.apiURL}api/Patient/SelectHearAbout`,
  updateOrderServices :`${environment.apiURL}api/Patient/UpdateOrderService`,
  DownloadPaymentList : `${environment.apiURL}api/Order/DownloadPaymentDetail`,
  DeleteOrderService : `${environment.apiURL}api/Order/DeleteOrderService`,
  CancelOrder: `${environment.apiURL}api/Order/CancelOrder`,
  GetPaymentReceipts : `${environment.apiURL}api/Order/GetPaymentReceipts`,
  ChangePassword:`${environment.apiURL}api/User/ChangePassword`,
  getAllFloorsList:`${environment.apiURL}api/Hospital/GetAllFloors`,
  getAllBedsList:`${environment.apiURL}api/Hospital/GetAllBads`,
  addspeciality:`${environment.apiURL}api/Hospital/getSpeciality`,
  addFloors:`${environment.apiURL}api/Hospital/SaveUpdateFloors`,
  deleteFloor:`${environment.apiURL}api/Hospital/DeleteFloors`,
  getAllServices:`${environment.apiURL}api/Service/GetAllService`,
  selectAllServicesByCategory: `${environment.apiURL}api/Service/SelectAllServicesByCategory`,
  getMedicationList:`${environment.apiURL}api/Service/GetMedication`,
  addServices:`${environment.apiURL}api/Service`,
  deleteServices:`${environment.apiURL}api/Service/Delete`,
  GetRoomsStatus:`${environment.apiURL}api/Hospital/GetRoomsStatus`,
  SaveUpdateRoom:`${environment.apiURL}api/Hospital/SaveUpdateRoom`,
  SaveUpdateBed:`${environment.apiURL}api/Hospital/SaveUpdateBad`,
  GetbedStatus:`${environment.apiURL}api/Hospital/GetbedStatus`,
  GetAllRooms:`${environment.apiURL}api/Hospital/GetAllRooms`,
  DeleteRoom:`${environment.apiURL}api/Hospital/DeleteRoom`,
  deleteBeds:`${environment.apiURL}api/Hospital/DeleteBad`,
  GetCycles:`${environment.apiURL}api/Order/GetCycles`,
  GetRoutes:`${environment.apiURL}api/Order/GetRoutes`,
  GetDuration:`${environment.apiURL}api/Order/GetDuration`,
  GetmedicationPatient:`${environment.apiURL}api/Patient/GetmedicationPatient`,
  getDoctorsOpAppointment:`${environment.apiURL}api/Appointment/InClinicByDateAndDoctCode`,
  getMedicationUnit:`${environment.apiURL}api/Service/GetMedicationUnit`,
  getUserTypeList:`${environment.apiURL}api/UserType/Active`,
  getUserList:`${environment.apiURL}api/User/Active`,
  addUser:`${environment.apiURL}api/User`,
  getRadiologyPatients:`${environment.apiURL}api/Patient/GetRadiologyPatient`,
  getLaboratory:`${environment.apiURL}api/Patient/GetLaboratoryPatient`,
  DeleteVisitNoteDetailsDocuments:`${environment.apiURL}api/Document/DeleteVisitNoteDetailsDocuments`,
  getSearchedPatient:`${environment.apiURL}api/Appointment/PatientByMRM`,
  specialtyBookingSlots:`${environment.apiURL}api/Specialities/SpecialtyBookingSlots`,
  getSpecialtyBookingSlots:`${environment.apiURL}api/Specialities/GetSpecialtyBookingSlots`,
  deleteSpecialtyBookingSlots:`${environment.apiURL}api/Specialities/DeleteSpecialtyBookingSlots`,
  getCategorization: `${environment.apiURL}api/Service/GetCategorization`,
  getConsumables: `${environment.apiURL}api/Service/GetConsumables`,
  ByDateStartDateEndDate : `${environment.apiURL}api/Appointment/ByDateStartDateEndDate`,
  changeOrderReportStatus : `${environment.apiURL}api/Order/ChangeOrderReportStatus`,
  OrderServiceOrderById : `${environment.apiURL}api/Order/OrderServiceOrderById`,
  DeleteOrderServiceById:`${environment.apiURL}api/Order/DeleteOrderServiceById`,
  specialtyDownload : `${environment.apiURL}api/Specialities/Download`,
  doctorsDownload : `${environment.apiURL}api/Doctors/Download`,
  floorsDownload : `${environment.apiURL}api/Hospital/FloorsDownload`,
  bedsDownload : `${environment.apiURL}api/Hospital/BedDownload`,
  roomDownload : `${environment.apiURL}api/Hospital/RoomDownload`,
  medicationsDownload : `${environment.apiURL}api/Service/DownloadMedications`,
  usersDownload : `${environment.apiURL}api/User/DownloadUsers`,
  bookingSlotsDownload : `${environment.apiURL}api/Specialities/DownloadSpecialtyBookingSlots`,
  serviceDownload : `${environment.apiURL}api/Service/DownloadService`,
  admittedPatientDownload:`${environment.apiURL}api/Patient/AdmittedPatientDownload`,
  dischargePatientDownload:`${environment.apiURL}api/Patient/DischargePatientDownload`,
  ActiveInactivePatient:`${environment.apiURL}api/Patient/ActiveInactivePatient`,
  selectAllActivePatients:`${environment.apiURL}api/Patient/SelectAllActivePatients`,
  allPatientRoomsAssignedList:`${environment.apiURL}api/Patient/AllPatientRoomsAssignedList`,
  allEmergencypatientRooms:`${environment.apiURL}api/Patient/AllEmergencypatientRooms`,
  allPatientDischargeList:`${environment.apiURL}api/Patient/AllPatientDischargeList`,
  getAllOrderBydate:`${environment.apiURL}api/Order/GetAllOrderBydate`,
  getLaboratoryPatient:`${environment.apiURL}api/Order/GetLaboratoryPatient`,
  getRadiologyPatient:`${environment.apiURL}api/Order/GetRadiologyPatient`,
  getAllUser:`${environment.apiURL}api/User/SelectAllUserByDate`,
  selectAllAppointmentByDate:`${environment.apiURL}api/Appointment/SelectAllAppointmentByDate`,
  allRegisterPatientsDownload:`${environment.apiURL}api/Patient/AllRegisterPatientsDownload`,
  allAdmittedPatientDownload:`${environment.apiURL}api/Patient/AllAdmittedPatientDownload`,
  allERAdmittedPatientDownload:`${environment.apiURL}api/Patient/AllERAdmittedPatientDownload`,
  allDischargePatientDownload:`${environment.apiURL}api/Patient/AllDischargePatientDownload`,
  allOrderBydateDownloads:`${environment.apiURL}api/Order/AllOrderBydateDownloads`,
  allLaboratoryPatientDownloads:`${environment.apiURL}api/Order/AllLaboratoryPatientDownloads`,
  allRadiologyPatientDownloads:`${environment.apiURL}api/Order/AllRadiologyPatientDownloads`,
  allAppointmentsDownload:`${environment.apiURL}api/Appointment/AllAppointmentsDownload`,
  allUSersDownload:`${environment.apiURL}api/User/DownloadUsersByDate`,
  getPostedBy:`${environment.apiURL}api/Order/GetAllPostby`,
  getDoctorForAppoinment:`${environment.apiURL}api/Appointment/GetGetDoctorForAppointment`,
  changeRadiologyStatus:`${environment.apiURL}api/Order/ChangeRadiologyStatus`
}


// api/Patient/InClinicPatientData
// FrontUtilityUrl: `${environment.apiURL}api/FrontUtility`,
// GetLogs: `${Modules.Utilities}/GetLogs`,
// GetAllApiRoutes: `${Modules.Utilities}/GetAllApiRoutes`,
// Dashboard: {
//   GetDash: `${Modules.Dashboard}/SelectDash`,
// },
// FrontUtility: { GetDownloadLink: `${Modules.FrontUtilityUrl}/DownloadLink` },
// export const ExternalUrls = {
//   IPAddress: `${environment.httpProtocol}api.ipify.org/?format=json`,
// };
